name: Format (Pull Request)
on:
  pull_request:
    branches:
      - master 
  workflow_dispatch:

jobs:
  format:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
      name: Checkout Code

    - name: Restore NuGet Packages
      run: dotnet restore

    - name: Format solution
      run: dotnet format --verify-no-changes --severity error
