name: Format (Pull Request)
on:
  pull_request:
    branches:
      - main 
  workflow_dispatch:

jobs:
  format:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout Code

    - name: Restore NuGet Packages
      run: dotnet restore src/VerifactuQr/VerifactuQr.sln

    - name: Format solution
      run: dotnet format src/VerifactuQr/VerifactuQr.sln --verify-no-changes --severity error